version: '3'

services:
  server:
    image: "chattimus"
    build:
      dockerfile: ./build/dev/Dockerfile
      context: .
    volumes: 
      - go-volume:/go/
      - .:/go/src/app/
    expose:
      - $SERVER_PORT
    command: ["air", "-c", "./build/dev/server.toml"]

  socket:
    image: "chattimus"
    build:
      dockerfile: ./build/dev/Dockerfile
      context: .
    volumes: 
      - go-volume:/go/
      - .:/go/src/app/
    expose:
      - $SOCKET_PORT
    command: ["air", "-c", "./build/dev/socket.toml"]

  redis:
    image: redis:alpine3.12

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./build/dev/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - $NGINX_PORT:80

  mongo:
    image: mongo
    volumes:
      - chattimus-database:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: chattimus

  mongo-express:
    image: mongo-express
    ports:
      - $MONGO_EXPRESS_PORT:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret

volumes:
  postgres-volume: {}
  go-volume: {}
  chattimus-database: {}
